name: chef-yum

services:
  db:
    image: postgres:16.4
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=chefyum
      - POSTGRES_PASSWORD=chefyum
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
